version: '3'

services:
    
  pgdb:
    image: postgres:13
    container_name: pgdb
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdatabase/:/var/lib/postgresql/data/
    restart: always


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - pgdb
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    restart: always

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - pgdb
    restart: always

volumes:
  pgdatabase: