# Generated by Django 3.2 on 2022-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
