# Generated by Django 3.2 on 2022-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_tweet_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(),
        ),
    ]
