# Generated by Django 3.2 on 2022-05-16 06:42

import ckeditor.fields
from django.db import migrations
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20220502_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_cryptography.fields.encrypt(ckeditor.fields.RichTextField(default='')),
        ),
    ]
