# Generated by Django 3.2 on 2022-05-16 06:52

import ckeditor.fields
from django.db import migrations
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_cryptography.fields.encrypt(ckeditor.fields.RichTextField(default='')),
        ),
    ]
