# Generated by Django 3.2 on 2022-04-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_tweet_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tags',
        ),
    ]
