# Generated by Django 3.2 on 2022-04-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_tweet_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweets_name',
            new_name='tweet_name',
        ),
    ]
