# Generated by Django 3.2 on 2022-05-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ada_1d',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterModelOptions(
            name='ada_1h',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='ada_30m',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='bnb_1d',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterModelOptions(
            name='bnb_1h',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='bnb_30m',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='btc_1d',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterModelOptions(
            name='btc_1h',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='btc_30m',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='eth_1d',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterModelOptions(
            name='eth_1h',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='eth_30m',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='ltc_1d',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterModelOptions(
            name='ltc_1h',
            options={'ordering': ['-Datetime']},
        ),
        migrations.AlterModelOptions(
            name='ltc_30m',
            options={'ordering': ['-Datetime']},
        ),
    ]
