# Generated by Django 3.2 on 2022-04-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ada_1d',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='ada_1h',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='ada_30m',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='bnb_1d',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='bnb_1h',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='bnb_30m',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='btc_1d',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='btc_1h',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='btc_30m',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='eth_1d',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='eth_1h',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='eth_30m',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='ltc_1d',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='ltc_1h',
            name='predict_model3',
        ),
        migrations.RemoveField(
            model_name='ltc_30m',
            name='predict_model3',
        ),
        migrations.AddField(
            model_name='ada_1d',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ada_1h',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ada_30m',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='bnb_1d',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='bnb_1h',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='bnb_30m',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='btc_1d',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='btc_1h',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='btc_30m',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='eth_1d',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='eth_1h',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='eth_30m',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ltc_1d',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ltc_1h',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ltc_30m',
            name='predict_MACD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
