# Generated by Django 3.2 on 2022-04-27 09:35

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
