# Generated by Django 3.2 on 2022-04-27 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='demoAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', django_cryptography.fields.encrypt(models.FloatField(default=100000))),
                ('btc', django_cryptography.fields.encrypt(models.FloatField(default=0))),
                ('eth', django_cryptography.fields.encrypt(models.FloatField(default=0))),
                ('bnb', django_cryptography.fields.encrypt(models.FloatField(default=0))),
                ('ada', django_cryptography.fields.encrypt(models.FloatField(default=0))),
                ('ltc', django_cryptography.fields.encrypt(models.FloatField(default=0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('option', django_cryptography.fields.encrypt(models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4))),
                ('coin', django_cryptography.fields.encrypt(models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('bnb', 'bnb'), ('ada', 'ada'), ('ltc', 'ltc')], max_length=3))),
                ('price', django_cryptography.fields.encrypt(models.FloatField(blank=True, null=True))),
                ('sell_amount', django_cryptography.fields.encrypt(models.FloatField(default=0, null=True))),
                ('buy_amount', django_cryptography.fields.encrypt(models.FloatField(default=0, null=True))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountTrade', to='demoAccount.demoaccount')),
            ],
            options={
                'ordering': ['-trade_at'],
            },
        ),
    ]
