# Generated by Django 3.2 on 2022-04-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='demoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=100000)),
                ('btc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('bnb', models.FloatField(default=0)),
                ('ada', models.FloatField(default=0)),
                ('ltc', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('option', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('coin', models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('bnb', 'bnb'), ('ada', 'ada'), ('ltc', 'ltc')], max_length=3)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sell_amount', models.FloatField(default=0, null=True)),
                ('buy_amount', models.IntegerField(default=0, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountTrade', to='demoAccount.demoaccount')),
            ],
        ),
    ]
