# Generated by Django 3.2 on 2022-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='coin',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('bnb', 'bnb'), ('ada', 'ada'), ('ltc', 'ltc')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trade',
            name='option',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4),
        ),
    ]
